[project]
name = "ad-insercao-massa-ad"
version = "0.1.0"
description = "Gera script para inserção em massa de usuários no ad."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openpyxl>=3.1.5",
    "pandas>=2.3.3",
]
